import type { Metadata } from "next";
import {Instrument_Sans, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";

import QueryProvider from "@/components/QueryProvider";
const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
})
const instrument = Instrument_Sans({
    subsets : ['latin']
})

const AuthProvider = ({ children }) => {
    return <SessionProvider>{children}</SessionProvider>
  };



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${instrument.className} ${bricolage.className} antialiased`}
      >
        <AuthProvider>

        <QueryProvider >

        {children}
        </QueryProvider>
        </AuthProvider>
      </body>

    </html>
  );
}
